/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Resource = {
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  resourceType?: "studio_space" | "equipment" | "rehearsal_room" | "recording_studio" | "meeting_room" | "other" | "room";
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    title?: string;
    description?: string;
    _type: "file";
    _key: string;
  }>;
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  hourlyRate?: number;
  dailyRate?: number;
  currency?: "usd" | "eur" | "gbp";
  capacity?: number;
  squareFootage?: number;
  features?: Array<string>;
  technicalSpecs?: {
    soundproofing?: boolean;
    acousticTreatment?: boolean;
    controlRoom?: boolean;
    instruments?: Array<string>;
  };
  equipmentDetails?: {
    brand?: string;
    model?: string;
    quantity?: number;
    condition?: "new" | "good" | "fair";
    requiresDeposit?: boolean;
    depositAmount?: number;
  };
  isActive?: boolean;
  medusaResourceId?: string;
  seo?: Seo;
};

export type Media = {
  _id: string;
  _type: "media";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: "whitePaper" | "caseStudy" | "guide" | "report" | "article" | "video" | "other";
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    title?: string;
    description?: string;
    _type: "file";
    _key: string;
  }>;
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  file?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  fileUrl?: string;
  videoUrl?: string;
  videoDuration?: number;
  publishedDate?: string;
  author?: string;
  tags?: Array<string>;
  seo?: Seo;
  downloadCount?: number;
  fileSize?: number;
  fileType?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    title?: string;
    description?: string;
    _type: "file";
    _key: string;
  }>;
  eventDate?: string;
  eventEndDate?: string;
  venue?: string;
  address?: string;
  city?: string;
  country?: string;
  capacity?: number;
  ticketPrice?: number;
  currency?: "usd" | "eur" | "gbp";
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  status?: "draft" | "published" | "cancelled" | "soldOut" | "upcoming" | "past";
  tags?: Array<string>;
  seo?: Seo;
  medusaProductId?: string;
  medusaVariantId?: string;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  openGraphImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    blank?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  _type: "image";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
  };
  media?: unknown;
  title?: string;
  description?: string;
  _type: "file";
  _key: string;
}>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Resource | Media | Event | Seo | BlockContent | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/queries.ts
// Variable: eventsQuery
// Query: *[_type == "event" && status == "published"] | order(eventDate desc) {    _id,    _createdAt,    _updatedAt,    title,    "slug": slug.current,    shortDescription,    description,    eventDate,    eventEndDate,    venue,    address,    city,    country,    capacity,    ticketPrice,    currency,    "featuredImage": featuredImage.asset->url,    "featuredImageAlt": featuredImage.alt,    status,    tags,    medusaProductId,    medusaVariantId,    seo  }
export type EventsQueryResult = Array<{
  _id: string;
  _createdAt: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  shortDescription: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    title?: string;
    description?: string;
    _type: "file";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }> | null;
  eventDate: string | null;
  eventEndDate: string | null;
  venue: string | null;
  address: string | null;
  city: string | null;
  country: string | null;
  capacity: number | null;
  ticketPrice: number | null;
  currency: "eur" | "gbp" | "usd" | null;
  featuredImage: string | null;
  featuredImageAlt: string | null;
  status: "published";
  tags: Array<string> | null;
  medusaProductId: string | null;
  medusaVariantId: string | null;
  seo: Seo | null;
}>;
// Variable: eventBySlugQuery
// Query: *[_type == "event" && slug.current == $slug][0] {    _id,    _createdAt,    _updatedAt,    title,    "slug": slug.current,    shortDescription,    description,    eventDate,    eventEndDate,    venue,    address,    city,    country,    capacity,    ticketPrice,    currency,    "featuredImage": featuredImage.asset->url,    "featuredImageAlt": featuredImage.alt,    "gallery": gallery[].asset->url,    status,    tags,    medusaProductId,    medusaVariantId,    seo  }
export type EventBySlugQueryResult = {
  _id: string;
  _createdAt: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  shortDescription: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    title?: string;
    description?: string;
    _type: "file";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }> | null;
  eventDate: string | null;
  eventEndDate: string | null;
  venue: string | null;
  address: string | null;
  city: string | null;
  country: string | null;
  capacity: number | null;
  ticketPrice: number | null;
  currency: "eur" | "gbp" | "usd" | null;
  featuredImage: string | null;
  featuredImageAlt: string | null;
  gallery: Array<string | null> | null;
  status: "cancelled" | "draft" | "past" | "published" | "soldOut" | "upcoming" | null;
  tags: Array<string> | null;
  medusaProductId: string | null;
  medusaVariantId: string | null;
  seo: Seo | null;
} | null;
// Variable: mediaQuery
// Query: *[_type == "media" && (!defined($category) || category == $category)] | order(publishedDate desc) {    _id,    _createdAt,    _updatedAt,    title,    "slug": slug.current,    category,    shortDescription,    description,    "featuredImage": featuredImage.asset->url,    "featuredImageAlt": featuredImage.alt,    "fileUrl": file.asset->url,    publishedDate,    author,    tags,    videoUrl,    videoDuration,    downloadCount,    fileSize,    fileType,    seo  }
export type MediaQueryResult = Array<{
  _id: string;
  _createdAt: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  category: "article" | "caseStudy" | "guide" | "other" | "report" | "video" | "whitePaper" | null;
  shortDescription: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    title?: string;
    description?: string;
    _type: "file";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }> | null;
  featuredImage: string | null;
  featuredImageAlt: string | null;
  fileUrl: string | null;
  publishedDate: string | null;
  author: string | null;
  tags: Array<string> | null;
  videoUrl: string | null;
  videoDuration: number | null;
  downloadCount: number | null;
  fileSize: number | null;
  fileType: string | null;
  seo: Seo | null;
}>;
// Variable: mediaBySlugQuery
// Query: *[_type == "media" && slug.current == $slug][0] {    _id,    _createdAt,    _updatedAt,    title,    "slug": slug.current,    category,    shortDescription,    description,    "featuredImage": featuredImage.asset->url,    "featuredImageAlt": featuredImage.alt,    "fileUrl": file.asset->url,    publishedDate,    author,    tags,    videoUrl,    videoDuration,    downloadCount,    fileSize,    fileType,    seo  }
export type MediaBySlugQueryResult = {
  _id: string;
  _createdAt: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  category: "article" | "caseStudy" | "guide" | "other" | "report" | "video" | "whitePaper" | null;
  shortDescription: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    title?: string;
    description?: string;
    _type: "file";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }> | null;
  featuredImage: string | null;
  featuredImageAlt: string | null;
  fileUrl: string | null;
  publishedDate: string | null;
  author: string | null;
  tags: Array<string> | null;
  videoUrl: string | null;
  videoDuration: number | null;
  downloadCount: number | null;
  fileSize: number | null;
  fileType: string | null;
  seo: Seo | null;
} | null;
// Variable: resourcesQuery
// Query: *[_type == "resource" && isActive == true && (!defined($type) || resourceType == $type)] | order(title asc) {    _id,    _createdAt,    _updatedAt,    title,    "slug": slug.current,    resourceType,    shortDescription,    hourlyRate,    dailyRate,    currency,    capacity,    squareFootage,    "featuredImage": featuredImage.asset->url,    "featuredImageAlt": featuredImage.alt,    features,    isActive,    medusaResourceId  }
export type ResourcesQueryResult = Array<{
  _id: string;
  _createdAt: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  resourceType: "equipment" | "meeting_room" | "other" | "recording_studio" | "rehearsal_room" | "room" | "studio_space" | null;
  shortDescription: string | null;
  hourlyRate: number | null;
  dailyRate: number | null;
  currency: "eur" | "gbp" | "usd" | null;
  capacity: number | null;
  squareFootage: number | null;
  featuredImage: string | null;
  featuredImageAlt: string | null;
  features: Array<string> | null;
  isActive: boolean | null;
  medusaResourceId: string | null;
}>;
// Variable: resourceBySlugQuery
// Query: *[_type == "resource" && slug.current == $slug][0] {    _id,    _createdAt,    _updatedAt,    title,    "slug": slug.current,    resourceType,    shortDescription,    description,    "featuredImage": featuredImage.asset->url,    "featuredImageAlt": featuredImage.alt,    "gallery": gallery[].asset->url,    hourlyRate,    dailyRate,    currency,    capacity,    squareFootage,    features,    technicalSpecs,    equipmentDetails,    isActive,    medusaResourceId,    seo  }
export type ResourceBySlugQueryResult = {
  _id: string;
  _createdAt: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  resourceType: "equipment" | "meeting_room" | "other" | "recording_studio" | "rehearsal_room" | "room" | "studio_space" | null;
  shortDescription: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    title?: string;
    description?: string;
    _type: "file";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }> | null;
  featuredImage: string | null;
  featuredImageAlt: string | null;
  gallery: Array<string | null> | null;
  hourlyRate: number | null;
  dailyRate: number | null;
  currency: "eur" | "gbp" | "usd" | null;
  capacity: number | null;
  squareFootage: number | null;
  features: Array<string> | null;
  technicalSpecs: {
    soundproofing?: boolean;
    acousticTreatment?: boolean;
    controlRoom?: boolean;
    instruments?: Array<string>;
  } | null;
  equipmentDetails: {
    brand?: string;
    model?: string;
    quantity?: number;
    condition?: "fair" | "good" | "new";
    requiresDeposit?: boolean;
    depositAmount?: number;
  } | null;
  isActive: boolean | null;
  medusaResourceId: string | null;
  seo: Seo | null;
} | null;
// Variable: studioSpacesQuery
// Query: *[_type == "resource" && isActive == true && resourceType in ["studio_space", "recording_studio", "rehearsal_room"]] | order(title asc) {    _id,    title,    "slug": slug.current,    resourceType,    shortDescription,    hourlyRate,    dailyRate,    currency,    capacity,    squareFootage,    "featuredImage": featuredImage.asset->url,    features,    technicalSpecs  }
export type StudioSpacesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  resourceType: "equipment" | "meeting_room" | "other" | "recording_studio" | "rehearsal_room" | "room" | "studio_space" | null;
  shortDescription: string | null;
  hourlyRate: number | null;
  dailyRate: number | null;
  currency: "eur" | "gbp" | "usd" | null;
  capacity: number | null;
  squareFootage: number | null;
  featuredImage: string | null;
  features: Array<string> | null;
  technicalSpecs: {
    soundproofing?: boolean;
    acousticTreatment?: boolean;
    controlRoom?: boolean;
    instruments?: Array<string>;
  } | null;
}>;
// Variable: equipmentQuery
// Query: *[_type == "resource" && isActive == true && resourceType == "equipment"] | order(title asc) {    _id,    title,    "slug": slug.current,    shortDescription,    hourlyRate,    dailyRate,    currency,    "featuredImage": featuredImage.asset->url,    equipmentDetails  }
export type EquipmentQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  shortDescription: string | null;
  hourlyRate: number | null;
  dailyRate: number | null;
  currency: "eur" | "gbp" | "usd" | null;
  featuredImage: string | null;
  equipmentDetails: {
    brand?: string;
    model?: string;
    quantity?: number;
    condition?: "fair" | "good" | "new";
    requiresDeposit?: boolean;
    depositAmount?: number;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"event\" && status == \"published\"] | order(eventDate desc) {\n    _id,\n    _createdAt,\n    _updatedAt,\n    title,\n    \"slug\": slug.current,\n    shortDescription,\n    description,\n    eventDate,\n    eventEndDate,\n    venue,\n    address,\n    city,\n    country,\n    capacity,\n    ticketPrice,\n    currency,\n    \"featuredImage\": featuredImage.asset->url,\n    \"featuredImageAlt\": featuredImage.alt,\n    status,\n    tags,\n    medusaProductId,\n    medusaVariantId,\n    seo\n  }\n": EventsQueryResult;
    "\n  *[_type == \"event\" && slug.current == $slug][0] {\n    _id,\n    _createdAt,\n    _updatedAt,\n    title,\n    \"slug\": slug.current,\n    shortDescription,\n    description,\n    eventDate,\n    eventEndDate,\n    venue,\n    address,\n    city,\n    country,\n    capacity,\n    ticketPrice,\n    currency,\n    \"featuredImage\": featuredImage.asset->url,\n    \"featuredImageAlt\": featuredImage.alt,\n    \"gallery\": gallery[].asset->url,\n    status,\n    tags,\n    medusaProductId,\n    medusaVariantId,\n    seo\n  }\n": EventBySlugQueryResult;
    "\n  *[_type == \"media\" && (!defined($category) || category == $category)] | order(publishedDate desc) {\n    _id,\n    _createdAt,\n    _updatedAt,\n    title,\n    \"slug\": slug.current,\n    category,\n    shortDescription,\n    description,\n    \"featuredImage\": featuredImage.asset->url,\n    \"featuredImageAlt\": featuredImage.alt,\n    \"fileUrl\": file.asset->url,\n    publishedDate,\n    author,\n    tags,\n    videoUrl,\n    videoDuration,\n    downloadCount,\n    fileSize,\n    fileType,\n    seo\n  }\n": MediaQueryResult;
    "\n  *[_type == \"media\" && slug.current == $slug][0] {\n    _id,\n    _createdAt,\n    _updatedAt,\n    title,\n    \"slug\": slug.current,\n    category,\n    shortDescription,\n    description,\n    \"featuredImage\": featuredImage.asset->url,\n    \"featuredImageAlt\": featuredImage.alt,\n    \"fileUrl\": file.asset->url,\n    publishedDate,\n    author,\n    tags,\n    videoUrl,\n    videoDuration,\n    downloadCount,\n    fileSize,\n    fileType,\n    seo\n  }\n": MediaBySlugQueryResult;
    "\n  *[_type == \"resource\" && isActive == true && (!defined($type) || resourceType == $type)] | order(title asc) {\n    _id,\n    _createdAt,\n    _updatedAt,\n    title,\n    \"slug\": slug.current,\n    resourceType,\n    shortDescription,\n    hourlyRate,\n    dailyRate,\n    currency,\n    capacity,\n    squareFootage,\n    \"featuredImage\": featuredImage.asset->url,\n    \"featuredImageAlt\": featuredImage.alt,\n    features,\n    isActive,\n    medusaResourceId\n  }\n": ResourcesQueryResult;
    "\n  *[_type == \"resource\" && slug.current == $slug][0] {\n    _id,\n    _createdAt,\n    _updatedAt,\n    title,\n    \"slug\": slug.current,\n    resourceType,\n    shortDescription,\n    description,\n    \"featuredImage\": featuredImage.asset->url,\n    \"featuredImageAlt\": featuredImage.alt,\n    \"gallery\": gallery[].asset->url,\n    hourlyRate,\n    dailyRate,\n    currency,\n    capacity,\n    squareFootage,\n    features,\n    technicalSpecs,\n    equipmentDetails,\n    isActive,\n    medusaResourceId,\n    seo\n  }\n": ResourceBySlugQueryResult;
    "\n  *[_type == \"resource\" && isActive == true && resourceType in [\"studio_space\", \"recording_studio\", \"rehearsal_room\"]] | order(title asc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    resourceType,\n    shortDescription,\n    hourlyRate,\n    dailyRate,\n    currency,\n    capacity,\n    squareFootage,\n    \"featuredImage\": featuredImage.asset->url,\n    features,\n    technicalSpecs\n  }\n": StudioSpacesQueryResult;
    "\n  *[_type == \"resource\" && isActive == true && resourceType == \"equipment\"] | order(title asc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    shortDescription,\n    hourlyRate,\n    dailyRate,\n    currency,\n    \"featuredImage\": featuredImage.asset->url,\n    equipmentDetails\n  }\n": EquipmentQueryResult;
  }
}
